In [1]:
import numpy as np
import pandas as pd

# 1. Array 데이터 (Numpy)

### 1-1. Array 데이터 생성

#### 1-1-1. 직접 값을 작성하여 Array 생성

1차원 배열 (벡터) 데이터

In [2]:
array_1d = [0,1,2]
array_1d

[0, 1, 2]

Array 연산 (list와 차이) : 배열 내 각 요소에 대한 연산을 수행 → 데이터 연산에 매우 효율적임

In [3]:
# array : numpy의 배열 데이터 형식 - 배열 내 요소(값) 별 연산에 효율적임

a = np.array([1,2,3])
b = np.array([3,3,3])
a+b

array([4, 5, 6])

In [4]:
# list : 파이썬 언어의 기본 배열 취급 데이터 형식

a = [1,2,3]
b = [3,3,3]
a+b

[1, 2, 3, 3, 3, 3]

2차원 배열 (행렬) 데이터

In [5]:
array_2d = np.array([[10,11,12],[20,21,22]])
array_2d

array([[10, 11, 12],
       [20, 21, 22]])

3차원 배열 데이터

In [6]:
array_3d = np.array([ [[10,11,12],[20,21,22]] , [[100,111,112],[120,121,122]] ])
array_3d

array([[[ 10,  11,  12],
        [ 20,  21,  22]],

       [[100, 111, 112],
        [120, 121, 122]]])

#### 1-1-2. 0 또는 1로 채워진 Array 생성 (실수형)

In [7]:
ary_01 = np.zeros(5)
ary_01

array([0., 0., 0., 0., 0.])

In [8]:
ary_02 = np.zeros((2,3))
ary_02

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
ary_11 = np.ones(5)
ary_11

array([1., 1., 1., 1., 1.])

In [10]:
ary_12 = np.ones((2,3))
ary_12

array([[1., 1., 1.],
       [1., 1., 1.]])

#### 1-1-3. 범위 및 단위값 지정하여 Array 생성

np.arange(a) : 0 부터 a 까지 (미만, a미포함) 배열 생성

In [11]:
ary_range_1 = np.arange(5)
ary_range_1

array([0, 1, 2, 3, 4])

np.arange(a,b) : a 부터(이상, a포함) b 까지 (미만, b미포함) 배열 생성

In [12]:
ary_range_2 = np.arange(1,10)
ary_range_2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

np.arange(a,b,c) : a 부터(이상, a포함) b 까지 (미만, b미포함) c 단위로 배열 생성

In [13]:
ary_range_3 = np.arange(1,10,0.5)
ary_range_3

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

#### numpy 아닌 Python 기본 범위지정 함수도 거의 유사함

range(a) : 0 부터 a까지 (미만, a미포함) '범위' 생성
* np.arange 와 다르게 배열로 출력할 수 없고, 범위로만 존재 (주로 반복구문에 활용)

In [14]:
range_1 = range(5)
range_1

range(0, 5)

range(a,b) : a 부터(이상, a포함) b 까지 (미만, b미포함) '범위' 생성
* np.arange 와 다르게 배열로 출력할 수 없고, 범위로만 존재 (주로 반복구문에 활용)

In [15]:
range_2 = range(1,10)
range_2

range(1, 10)

### 1-2. Array 데이터 인덱싱

#### 1-2-1. 특정 위치의 값 출력

In [16]:
ary_1d = np.arange(1,10)
ary_1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
ary_1d[0]

1

In [18]:
ary_2d = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
ary_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
ary_2d[0][0]

array([1, 2, 3])

1

1-2-2. 특정 범위의 배열 출력

In [22]:
ary_1d[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
ary_2d[1][0:2]

array([4, 5])

# 2. Data frame 데이터 (Pandas)

### 2-1. Data frame 데이터 생성 (일반적으로 DataFrame은 직접 생성하기 보다 다른 형식에서 변환)

2-1-1. 직접 값을 작성하여 생성

In [24]:
df_1 = pd.DataFrame([11,12,13])
df_1

    0
0  11
1  12
2  13

In [25]:
df_2 = pd.DataFrame({"A":['a','b','c'] , "B":[21,22,23] , "C":[31,32,33]})
df_2

   A   B   C
0  a  21  31
1  b  22  32
2  c  23  33

2-1-2. Array 데이터를 Data frame 형식으로 변환

In [26]:
ary_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
df_3 = pd.DataFrame(ary_2d)
df_3

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

### 2-2. Data frame 데이터 인덱싱

In [28]:
df_3.iloc[:2 , 0:3]

   0  1  2
0  1  2  3
1  4  5  6